### ISSUE TITLE
[Server] 게시물 리스트 조회, 게시물 상세 조회, 게시물 삭제, 좋아요 기능 구현

### ISSUE THREAD

**Issue by Hprogram** [Hprogram/community_server#5]
### **ISSUE**

- Group:  `server`
- Type: `feature`
- Detail: 게시물 기능 구현

### **TODO**

- [x]  게시물 리스트 조회
- [x]  게시물 상세 조회
- [x]  게시물 삭제 구현
- [x]  좋아요 기능 구현

**Comment by Hprogram** [comment]
완료.
